### ISSUE TITLE
Support: Shadow of the Demon Lord

### ISSUE THREAD

**Issue by Xacus** [illandril/FoundryVTT-hotbar-uses#10]
Cool module. I was thinking of making something similar for my system. Can I ask you to make support for Shadow of the Demon Lord?

game.system.id = demonlord

Talents: Uses data.uses.value and data.uses.max
Spells: Uses data.castings.value and data.castings.max

But is shown as used: 0/2, 1/2 or 2/2. So value is increased. You used 1 of 2 (1/2) and you used all today (2/2).

**Comment by illandril** [comment]
I'll look into it, but this will be low on my priority list since I don't play Shadow of the Demon Lord, so no guarantees, and it might be a while even if I do it.
I will accept pull requests if you (or anyone else) wants to implement support for this (or any other) system - I just ask that you comment here if you're going to do so before you start work on it, to minimize the risk of two people working on the same thing.

**Comment by Xacus** [comment]
I'll have a look at it.
