### ISSUE TITLE
Pathfinder attacks support

### ISSUE THREAD

**Issue by DeadLeaves** [illandril/FoundryVTT-hotbar-uses#23]
I would love if you could add support for attacks in pathfinder. It works perfectly fine for features and items. But in the pathfinder system you make attacks instead of rolling with a weapon item. 

DeadLeaves#7840 in discord if you want more info.

**Comment by illandril** [comment]
I'm assuming you meant PF2 because I don't see any separate attacks system for PF1.
For PF2 strikes, all I saw that would have a "uses" value is strikes with associated ammo, which are now shown (or will be in a few minutes when I create a new release).

If there are other strikes that should have uses calculated for them, please provide more details (see [my comment on Issue #18](https://github.com/illandril/FoundryVTT-hotbar-uses/issues/18#issuecomment-781512661) for details on what kind of information would be helpful).
