### ISSUE TITLE
Support for Pathfinder 2e

### ISSUE THREAD

**Issue by williamsfl350** [illandril/FoundryVTT-hotbar-uses#26]
Hi!

Love the module and just wanted to add my vote for Pathfinder 2e integration.

Thanks!

**Comment by illandril** [comment]
This module does work for Pathfinder 2e, but since I don't play or have much familiarity with the Pathfinder 2e system, there is definitely a chance that some things don't work as well as they should.

If you can give me specific examples of macros that should have uses that don't (or that are calculating using incorrectly), I'll see what I can do to fix them.

**Comment by illandril** [comment]
See [my comment on Issue #18](https://github.com/illandril/FoundryVTT-hotbar-uses/issues/18#issuecomment-781512661) for details on what kind of information would be helpful.

**Comment by illandril** [comment]
Since nobody has provided any examples of things that need to be changed for Pathfinder 2e, I'm going to close this under the assumption that Pathfinder 2e support is satisfactory. If anyone provides me with any specifics, I am certainly happy to make changes to improve Pathfinder 2e support, but without specifics, there's nothing I can do.
