### ISSUE TITLE
Build JS files into a bundle to reduce requests

### ISSUE THREAD

**Issue by 346184** [illandril/FoundryVTT-hotbar-uses#38]
Hey! While debugging the large number of requests causing infrastructure issues when loading into Foundry, I saw that the module currently needs 16 requests for me on each load into Foundry:

```
16 illandril-hotbar-uses
# 1 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/styles.css
# 2 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/init.js
# 3 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-system.js
# 4 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/ui.js
# 5 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/settings.js
# 6 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/dnd5e.js
# 7 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/pf1.js
# 8 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/pf2.js
# 9 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/demonlord.js
# 10 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/archmage.js
# 11 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/generic.js
# 12 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/specialty-modules.js
# 13 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/specialty-modules/magicitems.js
# 14 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/item-systems/item-system.js
# 15 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/scripts/specialty-modules/specialty-module.js
# 16 -> https://assets.forge-vtt.com/bazaar/modules/illandril-hotbar-uses/3.0.3/lang/en.json
```

Would be nice if you could bundle the JS files with a build step when distributing, so they are not all separate HTTP requests. If everyone does this, even 10 modules require 160 HTTP requests, and some people tend to have *way* more modules.

Thanks for the amazing module, been using it for a long time. :)

**Comment by illandril** [comment]
The Forge does a number of things that make "number of HTTP requests" not really an important metric.
1. It allows HTTP2, so requests can be multiplexed
2. It sets appropriate headers allowing the files to be cached
3. It uses a CDN, and every forge instance uses the same CDN, so if ANYONE is using the same version of a module near another player, the CDN will already have a local cache close to that player

I will eventually be converting this module into a Typescript project that will get bundled into a single `.js` file (like I have for most of my other modules already), so it will be 3 requests (`js`, `css`, `en.json`), but the effective impact of that on most users will be negligible (especially those that are already using The Forge or have otherwise set up their server effectively).

**Comment by Fallayn** [comment]
> It allows HTTP2, so requests can be multiplexed

That helps with hundreds of requests at the same time, not thousands, which is starting to be common for module heavy worlds with each module making a dozen requests

> It sets appropriate headers allowing the files to be cached

Less sure, but when I looked at the traffic, at least some cached assets still resulted in requests (with an `If-Modified-Since` header), so this helps with bandwith, but not number of requests

> It uses a CDN

Usage of Foundry should not require a hosting setup of that caliber, and eventually CDNs may block or reset requests if loading Foundry causes a storm of requests, I ran into this after all when Cloudflare had some issues that only happened with multiple hundreds of requests at the same time - so Foundry

> I will eventually be converting this module into a Typescript project that will get bundled into a single .js file

Great to hear! And also, I didn't want to suggest this is super critical or high priority, but it would be nice :) Thanks for all your work for the community!
